Vagrant.configure('2') do |config|
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
  config.vm.provider 'docker' do |d|
    d.image       = "thanandorn/vagrant-centos:7.4.1708"
    d.create_args = [ "--privileged",
                      "--dns","8.8.8.8",
                      "--dns","8.8.4.4"]
    d.has_ssh     = true
    d.cmd         = [ "/usr/sbin/init" ]
  end
end
